project:
  type: book
  output-dir: ../../../docs/R
  render: 
    - "*.qmd"

book:
  title: "AI-Assisted Statistics for Data Scientists"
  author: "Peter Bruce, Andrew Bruce, Peter Gedeck"
  chapters:
    - index.qmd
    - ch01.qmd
    - ch02.qmd
    - ch03.qmd
    - ch04.qmd
    - ch05.qmd
    - ch06.qmd
    - ch07.qmd
    - ch08.qmd
    - ch09.qmd
    - ch10.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    number-sections: false
    include-after-body:
      text: |
        <hr>
        <div role="contentinfo" aria-label="copyright" class="copyright" style="text-align:center;">Copyright &copy; 2017-2026  Peter Bruce, Andrew Bruce, Peter Gedeck</div>
        <script>
        document.querySelectorAll('.cell-output > pre').forEach(function(el) {
          el.setAttribute('tabindex', '0');
        });
        document.querySelectorAll('.sidebar-item-text.sidebar-link.text-start').forEach(function(el, idx) {
          el.setAttribute('aria-label', 'part ' + idx);
        });
        document.querySelectorAll('.sidebar-item-toggle').forEach(function(el, idx) {
          el.setAttribute('aria-label', 'part ' + idx + ' toggle');
        });
        document.querySelectorAll('#quarto-sidebar').forEach(function(el) {
          el.setAttribute('aria-label', 'Main site navigation');
        });
        document.querySelectorAll('.quarto-secondary-nav').forEach(function(el) {
          el.setAttribute('aria-label', 'Secondary navigation');
        });
        document.querySelectorAll('#TOC').forEach(function(el, idx) {
          el.setAttribute('aria-label', 'Table of Contents for the current page ' + idx);
        });
        </script>

engine: knitr
